// Menu data — all items mapped to local image assets
// Categories: Brunch, Food, Desserts, Bar

export interface MenuItemData {
  id: string;
  name: string;
  price: number;
  category: string;
  desc: string;
  image: string;
}

export interface MenuCategory {
  category: string;
  slug: string;
  heroImage: string;
  items: MenuItemData[];
}

const generateId = (category: string, name: string) =>
  `${category}-${name}`.toLowerCase().replace(/\s+/g, "-");

export const menuCategories: MenuCategory[] = [
  {
    category: "Brunch",
    slug: "brunch",
    heroImage: "/assets/pictures/menu/Brunch_Menu.webp",
    items: [
      {
        id: generateId("brunch", "The Full American"),
        name: "The Full American",
        price: 1650,
        category: "Brunch",
        desc: "Chicken & beef sausages, turkey bacon, fried eggs, hash browns, baked beans, grilled tomatoes, sautéed mushrooms",
        image: "/assets/pictures/food/Brunch/The Full American.webp",
      },
      {
        id: generateId("brunch", "Turkish Eggs"),
        name: "Turkish Eggs (Çılbır)",
        price: 1150,
        category: "Brunch",
        desc: "Creamy poached eggs in garlic-herb yogurt, Thai-bird chilli & chilli oil drizzle",
        image: "/assets/pictures/food/Brunch/Turkish Eggs.webp",
      },
      {
        id: generateId("brunch", "Poutine Shakshouka"),
        name: "Poutine Shakshouka",
        price: 1250,
        category: "Brunch",
        desc: "Fried eggs in spicy marinara with crispy fries, cheese curds & fresh herbs",
        image: "/assets/pictures/food/Brunch/Poutine Shakshouka.webp",
      },
      {
        id: generateId("brunch", "Croque Madame"),
        name: "Croque Madame",
        price: 1350,
        category: "Brunch",
        desc: "Classic French toasted sandwich with béchamel, gruyère, turkey ham & a fried egg",
        image: "/assets/pictures/food/Brunch/Croque Madame.webp",
      },
      {
        id: generateId("brunch", "Middle Eastern Poached Eggs"),
        name: "Middle Eastern Poached Eggs",
        price: 1250,
        category: "Brunch",
        desc: "Poached eggs on spiced labneh with za'atar, olive oil, sumac & warm flatbread",
        image: "/assets/pictures/food/Brunch/Middle Eastern Poached Eggs.webp",
      },
      {
        id: generateId("brunch", "Pancakes"),
        name: "Fluffy Pancakes",
        price: 1050,
        category: "Brunch",
        desc: "Buttermilk pancakes stacked high with maple syrup, fresh berries & whipped cream",
        image: "/assets/pictures/food/Brunch/Pancakes.webp",
      },
      {
        id: generateId("brunch", "Smoked Salmon Muffin"),
        name: "Smoked Salmon & Cream Cheese Muffin",
        price: 1350,
        category: "Brunch",
        desc: "Toasted English muffin topped with smoked salmon, herbed cream cheese, capers & dill",
        image: "/assets/pictures/food/Brunch/Smoked Salmon & Cream Cheese Muffin.webp",
      },
    ],
  },
  {
    category: "Food",
    slug: "food",
    heroImage: "/assets/pictures/menu/Food_Menu.webp",
    items: [
      {
        id: generateId("food", "Brisket Sandwich"),
        name: "Brisket Sandwich",
        price: 1550,
        category: "Food",
        desc: "Slow-smoked beef brisket, caramelized onions, pickles & tangy BBQ sauce on a brioche bun",
        image: "/assets/pictures/food/Brisket Sandwich.webp",
      },
      {
        id: generateId("food", "Caesar Salad"),
        name: "Caesar Salad",
        price: 1050,
        category: "Food",
        desc: "Crisp romaine, shaved parmesan, garlic croutons & house-made Caesar dressing",
        image: "/assets/pictures/food/Caesar Salad.webp",
      },
      {
        id: generateId("food", "Chicken Parmy Sandwich"),
        name: "Chicken Parmy Sandwich",
        price: 1450,
        category: "Food",
        desc: "Crispy chicken schnitzel, marinara, melted mozzarella & basil on toasted ciabatta",
        image: "/assets/pictures/food/Chicken Parmy Sandwich.webp",
      },
      {
        id: generateId("food", "Chicken Roulade"),
        name: "Chicken Roulade",
        price: 1750,
        category: "Food",
        desc: "Herb-stuffed chicken breast rolled with spinach & sun-dried tomatoes, served with jus",
        image: "/assets/pictures/food/Chicken Roulade.webp",
      },
      {
        id: generateId("food", "Mac & Cheese"),
        name: "Mac & Cheese",
        price: 1150,
        category: "Food",
        desc: "Creamy three-cheese baked macaroni with a golden breadcrumb crust",
        image: "/assets/pictures/food/Mac & Cheese.webp",
      },
      {
        id: generateId("food", "Moroccan Chicken"),
        name: "Moroccan Chicken",
        price: 1650,
        category: "Food",
        desc: "Slow-braised chicken thighs with preserved lemon, olives, apricots & fragrant couscous",
        image: "/assets/pictures/food/Moroccan Chicken.webp",
      },
      {
        id: generateId("food", "Mulligatawny Soup"),
        name: "Mulligatawny Soup",
        price: 850,
        category: "Food",
        desc: "A rich, spiced lentil & chicken soup with coconut milk, ginger & fresh coriander",
        image: "/assets/pictures/food/Mulligatawny Soup.webp",
      },
      {
        id: generateId("food", "Penna Arrabbiata"),
        name: "Penna Arrabbiata",
        price: 1250,
        category: "Food",
        desc: "Penne in spicy tomato sauce with garlic, chilli flakes, fresh basil & parmesan shavings",
        image: "/assets/pictures/food/Penna Arrabbiata.webp",
      },
      {
        id: generateId("food", "Pesto Sandwich"),
        name: "Pesto Sandwich",
        price: 1150,
        category: "Food",
        desc: "Grilled chicken, fresh basil pesto, mozzarella, sun-dried tomatoes on sourdough",
        image: "/assets/pictures/food/Pesto Sandwich.webp",
      },
      {
        id: generateId("food", "Philly Cheesesteak Sandwich"),
        name: "Philly Cheesesteak",
        price: 1450,
        category: "Food",
        desc: "Shaved beef, sautéed peppers & onions, melted provolone on a toasted hoagie roll",
        image: "/assets/pictures/food/Philly Cheesesteak Sandwich.webp",
      },
      {
        id: generateId("food", "Ramen"),
        name: "Ramen",
        price: 1350,
        category: "Food",
        desc: "Rich tonkotsu broth with noodles, chashu pork, soft-boiled egg, nori & scallions",
        image: "/assets/pictures/food/Ramen.webp",
      },
      {
        id: generateId("food", "Roasted Tomato Soup"),
        name: "Roasted Tomato Soup",
        price: 850,
        category: "Food",
        desc: "Fire-roasted tomatoes blended with basil, garlic & cream, served with grilled bread",
        image: "/assets/pictures/food/Roasted Tomato Soup.webp",
      },
      {
        id: generateId("food", "Seafood Chowder"),
        name: "Seafood Chowder",
        price: 1350,
        category: "Food",
        desc: "Creamy chowder loaded with prawns, fish, mussels, potatoes & fresh dill",
        image: "/assets/pictures/food/Seafood Chowder.webp",
      },
      {
        id: generateId("food", "Sour Cream Jacket Potato"),
        name: "Sour Cream Jacket Potato",
        price: 950,
        category: "Food",
        desc: "Baked potato split open with butter, sour cream, chives, cheddar & turkey bacon bits",
        image: "/assets/pictures/food/Sour Cream Jacket Potato.webp",
      },
      {
        id: generateId("food", "Spicy Seafood Linguine"),
        name: "Spicy Seafood Linguine",
        price: 1650,
        category: "Food",
        desc: "Linguine tossed with prawns, calamari, mussels in a spicy tomato & white wine sauce",
        image: "/assets/pictures/food/Spicy Seafood Linguine.webp",
      },
      {
        id: generateId("food", "Sticky Toffee Pudding"),
        name: "Sticky Toffee Pudding",
        price: 950,
        category: "Food",
        desc: "Warm date sponge drenched in toffee sauce with a scoop of vanilla bean ice cream",
        image: "/assets/pictures/food/Sticky Toffee Pudding.webp",
      },
    ],
  },
  {
    category: "Desserts",
    slug: "desserts",
    heroImage: "/assets/pictures/menu/Desserts.webp",
    items: [
      {
        id: generateId("desserts", "Apple Crumble"),
        name: "Apple Crumble",
        price: 950,
        category: "Desserts",
        desc: "Spiced apple filling under a buttery oat crumble, served warm with vanilla custard",
        image: "/assets/pictures/dessert/Apple Crumble.webp",
      },
      {
        id: generateId("desserts", "Bread Pudding"),
        name: "Bread Pudding",
        price: 850,
        category: "Desserts",
        desc: "Classic baked bread pudding with raisins, cinnamon & a drizzle of caramel sauce",
        image: "/assets/pictures/dessert/Bread Pudding.webp",
      },
      {
        id: generateId("desserts", "Brownie Cheesecake"),
        name: "Brownie Cheesecake",
        price: 1050,
        category: "Desserts",
        desc: "Rich chocolate brownie base with creamy cheesecake swirl & dark chocolate ganache",
        image: "/assets/pictures/dessert/Brownie Cheesecake.webp",
      },
      {
        id: generateId("desserts", "Cookie Island"),
        name: "Cookie Island",
        price: 950,
        category: "Desserts",
        desc: "Warm giant cookie loaded with chocolate chips, served with ice cream & chocolate drizzle",
        image: "/assets/pictures/dessert/Cookie Island.webp",
      },
      {
        id: generateId("desserts", "Lisbon Cake"),
        name: "Lisbon Cake",
        price: 850,
        category: "Desserts",
        desc: "Portuguese-inspired custard cake with a caramelized top & hint of cinnamon",
        image: "/assets/pictures/dessert/Lisbon Cake.webp",
      },
      {
        id: generateId("desserts", "Molten Lava"),
        name: "Molten Lava Cake",
        price: 1150,
        category: "Desserts",
        desc: "Warm chocolate fondant with a gooey molten centre, dusted cocoa & vanilla ice cream",
        image: "/assets/pictures/dessert/Molten Lava.webp",
      },
      {
        id: generateId("desserts", "Panna Cotta"),
        name: "Panna Cotta",
        price: 850,
        category: "Desserts",
        desc: "Silky Italian vanilla cream dessert topped with seasonal berry compote",
        image: "/assets/pictures/dessert/Panna Cotta.webp",
      },
      {
        id: generateId("desserts", "San Sebastian Cheesecake"),
        name: "San Sebastian Cheesecake",
        price: 1150,
        category: "Desserts",
        desc: "Basque burnt cheesecake with a caramelized exterior and creamy, custardy centre",
        image: "/assets/pictures/dessert/San Sebastian Cheesecake.webp",
      },
    ],
  },
  {
    category: "Bar",
    slug: "bar",
    heroImage: "/assets/pictures/menu/Bar.webp",
    items: [
      {
        id: generateId("bar", "Cookie Butter Latte"),
        name: "Cookie Butter Latte",
        price: 750,
        category: "Bar",
        desc: "Espresso blended with creamy cookie butter, steamed milk & a biscoff crumble topping",
        image: "/assets/pictures/bar/Cookie Butter Latte.webp",
      },
      {
        id: generateId("bar", "Grapefruit & Apple Mockarita"),
        name: "Grapefruit & Apple Mockarita",
        price: 650,
        category: "Bar",
        desc: "Refreshing grapefruit & green apple mocktail with lime, mint & a salted rim",
        image: "/assets/pictures/bar/Grapefruit & Apple Mockarita.webp",
      },
      {
        id: generateId("bar", "Iced Banana Cream Latte"),
        name: "Iced Banana Cream Latte",
        price: 750,
        category: "Bar",
        desc: "Cold espresso with banana cream, oat milk & a swirl of caramel over ice",
        image: "/assets/pictures/bar/Iced Banana Cream Latte.webp",
      },
      {
        id: generateId("bar", "Iced Candy Corn Latte"),
        name: "Iced Candy Corn Latte",
        price: 700,
        category: "Bar",
        desc: "Playful vanilla & caramel layered iced latte with candy corn syrup & cream",
        image: "/assets/pictures/bar/Iced Candy Corn Latte.webp",
      },
      {
        id: generateId("bar", "Iced Mango Coconut Matcha"),
        name: "Iced Mango Coconut Matcha",
        price: 800,
        category: "Bar",
        desc: "Ceremonial matcha with coconut milk, mango purée & tropical flavours over ice",
        image: "/assets/pictures/bar/Iced Mango Coconut Matcha.webp",
      },
      {
        id: generateId("bar", "Iced Matcha Frappe"),
        name: "Iced Matcha Frappé",
        price: 750,
        category: "Bar",
        desc: "Blended matcha with milk, ice & a touch of vanilla, topped with whipped cream",
        image: "/assets/pictures/bar/Iced Matcha Frappe.webp",
      },
      {
        id: generateId("bar", "Iced Spiced Apple Cinnamon Latte"),
        name: "Iced Spiced Apple Cinnamon Latte",
        price: 750,
        category: "Bar",
        desc: "Cold brew with spiced apple syrup, cinnamon, oat milk & a caramel drizzle",
        image: "/assets/pictures/bar/Iced Spiced Apple Cinnamon Latte.webp",
      },
      {
        id: generateId("bar", "Iced Strawberry Matcha Cloud Latte"),
        name: "Iced Strawberry Matcha Cloud Latte",
        price: 800,
        category: "Bar",
        desc: "Layered strawberry purée, matcha & fluffy cloud foam for a dreamy iced drink",
        image: "/assets/pictures/bar/Iced Strawberry Matcha Cloud Latte.webp",
      },
      {
        id: generateId("bar", "Smores Mini Mint"),
        name: "S'mores Mini Mint",
        price: 700,
        category: "Bar",
        desc: "Hot chocolate with toasted marshmallow, graham cracker crumbs & fresh mint",
        image: "/assets/pictures/bar/Smores Mini Mint.webp",
      },
      {
        id: generateId("bar", "Spiced Orange Hot Chocolate"),
        name: "Spiced Orange Hot Chocolate",
        price: 650,
        category: "Bar",
        desc: "Rich dark hot chocolate infused with orange zest, cinnamon & a hint of chilli",
        image: "/assets/pictures/bar/Spiced Orange Hot Chocolate.webp",
      },
      {
        id: generateId("bar", "Tiramisu Affogato"),
        name: "Tiramisu Affogato",
        price: 850,
        category: "Bar",
        desc: "Mascarpone gelato drowned in a shot of hot espresso with cocoa & ladyfinger crumbs",
        image: "/assets/pictures/bar/Tiramisu Affogato.webp",
      },
      {
        id: generateId("bar", "Vanilla Spiced Matcha"),
        name: "Vanilla Spiced Matcha",
        price: 750,
        category: "Bar",
        desc: "Warm ceremonial matcha with vanilla bean, cardamom, steamed milk & honey",
        image: "/assets/pictures/bar/Vanilla Spiced Matcha.webp",
      },
    ],
  },
];
